### PR TITLE
[SPVR-60][SPVR-15] Network list

### PR DESCRIPTION
**Pull request by Aceralon**
Needs https://github.com/projecteru2/libyavirt/pull/32

### CODE REVIEW

**Comment by anrs** [comment]
LGTM

**Comment by CMGS** [comment]
but still WIP

**Comment by Aceralon** [comment]
> but still WIP

not after projecteru2/libyavirt#32 merged

**Comment by CMGS** [comment]
still  WIP?

**Comment by Aceralon** [comment]
> still WIP?

libyavirt is not merged yet.

**Pull request merged**
